/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "ink": "#0a0a0c",
        "ink-2": "#101014",
        "panel": "#141419",
        "line": "#26262d",
        "bone": "#f3f1ee",
        "mute": "#9a9aa5",
        "mute-2": "#5e5e6a",
        "red": "#ed1c24",
        "red-deep": "#a40e14",
        "red-soft": "#ff5057",
        "signal": "#4f7cff",
        "good": "#3fd07e",
        "wa": "#25d366",
        "primary": "#ed1c24",
        "background": "#0a0a0c",
        "surface-variant": "#15151c",
        "surface-container": "#101015",
        "surface-container-low": "#0a0a0c",
        "surface-container-lowest": "#060608",
        "surface-container-high": "#1a1a23",
        "surface-container-highest": "#1f1f2a",
        "surface-bright": "#252530",
        "surface-dim": "#0a0a0c",
        "surface": "#0a0a0c",
        "on-surface": "#f3f1ee",
        "on-surface-variant": "#9a9aa7",
        "on-background": "#f3f1ee",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#9a9aa7",
        "secondary": "#9a9aa7",
        "secondary-container": "#15151c",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#9a9aa7",
        "tertiary": "#4f7cff",
        "tertiary-container": "#15151c",
        "error": "#ed1c24",
        "error-container": "#1a0506",
        "outline": "#26262f",
        "outline-variant": "#1f1f2a",
        "inverse-surface": "#f3f1ee",
        "inverse-on-surface": "#0a0a0c",
        "inverse-primary": "#ed1c24",
        "primary-container": "rgba(237,28,36,0.15)",
        "surface-tint": "#ed1c24",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "0.75rem"
      },
      spacing: {
        base: "4px",
        margin: "24px",
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "40px",
        gutter: "16px",
        "gutter-mobile": "16px",
        "margin-mobile": "16px",
        unit: "8px",
        "max-width": "1100px",
        "gutter-desktop": "28px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "display": ["'Saira Condensed'", "sans-serif"],
        "body": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"],
        "label-md": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "headline-xl": ["'Saira Condensed'", "sans-serif"],
        "headline-lg-mobile": ["'Saira Condensed'", "sans-serif"],
        "headline-md": ["'Saira Condensed'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "headline-lg": ["'Saira Condensed'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "body-sm": ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        "label-caps": ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-xl": ["clamp(3.2rem, 11vw, 8rem)", { lineHeight: "0.92", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-lg-mobile": ["clamp(2.3rem, 6vw, 4rem)", { lineHeight: "0.97", fontWeight: "800" }],
        "headline-md": ["1.4rem", { lineHeight: "1.02", fontWeight: "700" }],
        "body-lg": ["clamp(1.08rem, 2.4vw, 1.4rem)", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["clamp(2.3rem, 6vw, 4rem)", { lineHeight: "0.97", letterSpacing: "-0.005em", fontWeight: "800" }],
        "body-md": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
