/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001d32",
        "surface-container-lowest": "#0D131F",
        "surface-bright": "#222D41",
        "tertiary-fixed-dim": "#96ccff",
        "outline": "#b08782",
        "on-secondary": "#ffffff",
        "primary": "#ff1f1f",
        "on-primary-container": "#ffffff",
        "surface-container-low": "#1B2538",
        "surface-container-highest": "#303C52",
        "tertiary": "#96ccff",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-surface-variant": "#C8D1E1",
        "secondary-fixed": "#e4e2e1",
        "inverse-on-surface": "#0a0a0a",
        "on-tertiary-container": "#002c48",
        "secondary-container": "#1E293B",
        "primary-fixed-dim": "#ffb4aa",
        "primary-fixed": "#ffdad5",
        "on-surface": "#ffffff",
        "surface-container": "#1D273A",
        "primary-container": "#ff1f1f",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "on-error": "#ffffff",
        "tertiary-container": "#2a97e2",
        "tertiary-fixed": "#cee5ff",
        "surface-tint": "#ff1f1f",
        "on-primary-fixed-variant": "#930006",
        "inverse-primary": "#c0000c",
        "surface-variant": "#1E293B",
        "inverse-surface": "#ffffff",
        "outline-variant": "#2E3A4F",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#004a76",
        "background": "#151E2E",
        "surface-container-high": "#253147",
        "on-error-container": "#ffdad6",
        "on-background": "#ffffff",
        "on-secondary-container": "#b6b5b4",
        "on-tertiary": "#003353",
        "secondary": "#c8c6c5",
        "on-primary-fixed": "#410001",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-dim": "#151E2E",
        "surface": "#151E2E"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        base: "4px",
        margin: "24px",
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "40px",
        gutter: "16px",
        "gutter-mobile": "16px",
        "margin-mobile": "16px",
        unit: "8px",
        "max-width": "1440px",
        "gutter-desktop": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}